DELIMITER $$

CREATE FUNCTION calculate_bonus(salary DECIMAL(10,2)) 
RETURNS DECIMAL(10,2)
DETERMINISTIC
BEGIN
    RETURN salary * 0.10;
END $$

DELIMITER ;

DELIMITER $$

CREATE FUNCTION random_bonus(salary DECIMAL(10,2)) 
RETURNS DECIMAL(10,2)
NOT DETERMINISTIC
READS SQL DATA
BEGIN
    RETURN salary * (RAND() * 0.2);
END $$

DELIMITER ;

